export interface GroqChatOptions {
  messages: Array<{ role: 'system' | 'user' | 'assistant'; content: string }>;
  model?: string;
  temperature?: number;
  max_tokens?: number;
  customApiKey?: string;
}

export const GROQ_STORAGE_KEYS = {
  API_KEY: 'kurdo_groq_api_key',
  MODEL: 'kurdo_groq_model',
  AUTO_EXECUTE: 'kurdo_groq_auto_execute',
};

export const POPULAR_GROQ_MODELS = [
  { id: 'qwen/qwen3.6-27b', name: 'Qwen 3.6 27B (qwen/qwen3.6-27b - فەرمی و دەستنیشانکراو)', isRecommended: true },
  { id: 'qwen/qwen3.8-27b', name: 'Qwen 3.8 27B (qwen/qwen3.8-27b - بەهێزترین و نوێترین)' },
  { id: 'openai/gpt-oss-120b', name: 'GPT OSS 120B (OpenAI / Groq)' },
  { id: 'allam-2-7b', name: 'Allam 2 7B (Arabic / Multilingual)' },
];

export function getSanitizedGroqModel(rawModel?: string | null): string {
  if (!rawModel) return 'qwen/qwen3.6-27b';
  const clean = rawModel.trim();
  if (clean === 'qwen-2.5-32b' || clean === 'qwen/qwen3.6' || clean === 'qwen3.6' || clean === 'qwen-qwq-32b' || clean === 'qwen-2.5-coder-32b') {
    return 'qwen/qwen3.6-27b';
  }
  if (clean === 'qwen/qwen3.8' || clean === 'qwen3.8') {
    return 'qwen/qwen3.8-27b';
  }
  return clean;
}

export async function sendGroqChat(options: GroqChatOptions): Promise<{
  content: string;
  thinking?: string;
  modelUsed: string;
  rawResponse?: any;
}> {
  const customApiKey = options.customApiKey || localStorage.getItem(GROQ_STORAGE_KEYS.API_KEY) || '';
  const storedModel = localStorage.getItem(GROQ_STORAGE_KEYS.MODEL);
  const preferredModel = getSanitizedGroqModel(options.model || storedModel || 'qwen/qwen3.6-27b');

  // Keep localStorage sanitized
  if (storedModel && storedModel !== preferredModel && (storedModel.includes('2.5') || storedModel === 'qwen/qwen3.6')) {
    localStorage.setItem(GROQ_STORAGE_KEYS.MODEL, preferredModel);
  }

  const makeRequest = async (modelToUse: string, tokenLimit?: number) => {
    const res = await fetch('/api/groq/chat', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        messages: options.messages,
        model: modelToUse,
        temperature: options.temperature ?? 0.2,
        max_tokens: tokenLimit ?? options.max_tokens ?? 800,
        customApiKey: customApiKey || undefined,
      }),
    });

    const data = await res.json();
    return { res, data };
  };

  // Attempt with preferred model
  let result = await makeRequest(preferredModel);

  // If model not found or decommissioned, try fallback to qwen/qwen3.6-27b or qwen/qwen3.8-27b
  if (!result.res.ok && result.data?.error) {
    const errMsg = String(result.data.error).toLowerCase();
    if (errMsg.includes('decommissioned') || errMsg.includes('not found') || errMsg.includes('does not exist')) {
      const fallback = preferredModel !== 'qwen/qwen3.6-27b' ? 'qwen/qwen3.6-27b' : 'qwen/qwen3.8-27b';
      console.warn(`Model ${preferredModel} returned decommissioned/not found on Groq, retrying with ${fallback}...`);
      result = await makeRequest(fallback);
      if (result.res.ok) {
        localStorage.setItem(GROQ_STORAGE_KEYS.MODEL, fallback);
      }
    } else if (errMsg.includes('rate_limit_exceeded') || errMsg.includes('tokens per minute')) {
      // Retry with 500 max_tokens
      console.warn('Rate limit token exceeded, retrying with 500 max_tokens...');
      result = await makeRequest(preferredModel, 500);
    }
  }

  if (!result.res.ok) {
    throw new Error(result.data?.error || `هەڵەی پەیوەندی بە Groq API (${result.res.status})`);
  }

  const rawChoice = result.data.choices?.[0]?.message?.content || '';
  
  // Extract <think> reasoning if generated by Qwen reasoning models
  let thinking = '';
  let cleanContent = rawChoice;
  const thinkMatch = rawChoice.match(/<think>([\s\S]*?)<\/think>/i);
  if (thinkMatch) {
    thinking = thinkMatch[1].trim();
    cleanContent = rawChoice.replace(/<think>[\s\S]*?<\/think>/gi, '').trim();
  }

  return {
    content: cleanContent || rawChoice,
    thinking,
    modelUsed: result.data.model || preferredModel,
    rawResponse: result.data,
  };
}

export async function checkGroqStatus(): Promise<{ hasGroqKey: boolean }> {
  try {
    const res = await fetch('/api/health');
    if (res.ok) {
      const data = await res.json();
      return { hasGroqKey: !!data.hasGroqKey };
    }
  } catch (err) {
    console.error('Health check failed:', err);
  }
  return { hasGroqKey: false };
}
